//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLifeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloVehiculo
    {
        public ModeloVehiculo()
        {
            this.MarcaModeloVehiculo = new HashSet<MarcaModeloVehiculo>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MarcaModeloVehiculo> MarcaModeloVehiculo { get; set; }
    }
}
