//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLifeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionComuna
    {
        public RegionComuna()
        {
            this.Vivienda = new HashSet<Vivienda>();
        }
    
        public int IdRegion { get; set; }
        public int IdComuna { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Vivienda> Vivienda { get; set; }
    }
}
